title: Mars' Blog
description: Mars' Blog for sharing recommendation system, computational advertising, multimedia mining and knowledge graph.
google_analytics: 
show_downloads: true
theme: pacman

gems:
  - jekyll-mentions
